"area: backend":
  - changed-files:
      - any-glob-to-any-file:
          - "src/**"
          - "test/**"
          - "nest-cli.json"
          - "tsconfig*.json"

"area: ui":
  - changed-files:
      - any-glob-to-any-file:
          - "ui/**"

"area: docs":
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "docs/**"
          - ".local/**"

"area: infra":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "package.json"
          - "pnpm-lock.yaml"